#pragma once

#define OLED_DISPLAY_128x32
#define I2C1_SCL_PIN GP3
#define I2C1_SDA_PIN GP2
#define OLED_UPDATE_INTERVAL 1

// #define NUM_ENCODERS 1
#define NUMBER_OF_ENCODERS 1
#define ENCODER_A_PINS {GP23}
#define ENCODER_B_PINS {GP20}

#define EC11_BUTTON_PIN GP22
#define ENCODER_MAP_KEY_DELAY 10
// #define ENCODER_DIRECTION_FLIP
// #define ENCODER_RESOLUTION 4
// #define ENCODER_MAP_KEY_DELAY 10
